// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/resources/chords": {
    params: {};
  };
  "/resources/scales": {
    params: {};
  };
  "/resources/mode-quiz": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/resources/chords" | "/resources/scales" | "/resources/mode-quiz";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/Chords.tsx": {
    id: "routes/Chords";
    page: "/resources/chords";
  };
  "routes/Scales.tsx": {
    id: "routes/Scales";
    page: "/resources/scales";
  };
  "routes/ModeQuiz.tsx": {
    id: "routes/ModeQuiz";
    page: "/resources/mode-quiz";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/Chords": typeof import("./src/routes/Chords.tsx");
  "routes/Scales": typeof import("./src/routes/Scales.tsx");
  "routes/ModeQuiz": typeof import("./src/routes/ModeQuiz.tsx");
};