// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/resources": {
    params: {};
  };
  "/scale-finder": {
    params: {};
  };
  "/chords": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/resources" | "/scale-finder" | "/chords";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/Resources.tsx": {
    id: "routes/Resources";
    page: "/resources";
  };
  "routes/ScaleFinder.tsx": {
    id: "routes/ScaleFinder";
    page: "/scale-finder";
  };
  "routes/Chords.tsx": {
    id: "routes/Chords";
    page: "/chords";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/Resources": typeof import("./src/routes/Resources.tsx");
  "routes/ScaleFinder": typeof import("./src/routes/ScaleFinder.tsx");
  "routes/Chords": typeof import("./src/routes/Chords.tsx");
};