// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/button": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/button";
  };
  "routes/button.tsx": {
    id: "routes/button";
    page: "/button";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/button": typeof import("./app/routes/button.tsx");
};